#!/bin/bash

WWW_PORT="8081"
WWW_PATH="/data/games/retroshit/scumm_games/"

case $1 in
start)
cd $WWW_PATH
nohup python -m SimpleHTTPServer $WWW_PORT >> /tmp/nohup.log 2>&1 &
sleep 2
stat=`netstat -tlpn | grep $WWW_PORT | grep "python" | cut -d":" -f2 | cut -d" " -f1`
if [[ $WWW_PORT -eq $stat ]]; then
sock=`netstat -tlpn | grep $WWW_PORT | grep "python"`
echo -e "Server is running:\n$sock"
else
echo -e "Server is stopped"
fi
;;

stop)
pid=`ps -ax | grep "[S]impleHTTPServer $WWW_PORT"| awk ‘{print $1}’`
kill -9 $pid 2>/dev/null
rm -f /tmp/nohup.log
stat=`netstat -tlpn | grep $WWW_PORT | grep "python"| cut -d":" -f2 | cut -d" " -f1`
if [[ $WWW_PORT -eq $stat ]]; then
sock=`netstat -tlpn | grep $WWW_PORT | grep "python"`
echo -e "Server is still running:\n$sock"
else
echo -e "Server has stopped"
fi

;;

status)
stat=`netstat -tlpn |grep $WWW_PORT| grep "python" | cut -d":" -f2 | cut -d" " -f1`
if [[ $WWW_PORT -eq $stat ]]; then
sock=`netstat -tlpn | grep $WWW_PORT | grep "python"`
echo -e "Server is running:\n$sock"
else
echo -e "Server is stopped"
fi
;;
*)
echo "Use $0 start|stop|status"
;;
esac
