#!/bin/sh
#
#            _        _
#  _ __ ___ | |_ __ _| |_ ___     ___  ___ _ __ ___  ___ _ __
# | '__/ _ \| __/ _` | __/ _ \   / __|/ __| '__/ _ \/ _ \ '_ \
# | | | (_) | || (_| | ||  __/   \__ \ (__| | |  __/  __/ | | |
# |_|  \___/ \__\__,_|\__\___|___|___/\___|_|  \___|\___|_| |_|
#                           |_____|
#

# Para rotar rápido la pantalla

choice=$(echo -e "Normal\nRight\nLeft\nInverted" | dmenu -fn "$dmenu_font" -i -p "Rotar la pantalla: ")

case $choice in
	Normal) xrandr -o normal;;
	Right) xrandr -o right;;
	Left) xrandr -o left;;
	Inverted) xrandr -o inverted;;
esac

