#!/bin/sh

# Toma un video y le baja la calidad para poder compartirlo
# más fácilmente

in="$1"
out="$(echo "$in" | sed 's/\....$//1')-shareable.mp4"
ffmpeg -loglevel 0 -i "$in" -c:a libopus -b:a 36k -vcodec libx264 -profile:v baseline -level 3.0 -c:a aac -pix_fmt yuv420p -crf 35 "$out" &&
echo -e "Done $RED✔$NC\nNuevo archivo: "$out""
[ -f "$out" ] && dragon -x "$out" &
