#!/bin/sh

#  _
# | |_ __ _  __ _  ___  __ _ _ __
# | __/ _` |/ _` |/ _ \/ _` | '__|
# | || (_| | (_| |  __/ (_| | |
#  \__\__,_|\__, |\___|\__,_|_|
#           |___/

i=0
total=$(cat $1 | wc -l)
while read -r x
do
	autor="JRR Tolkien"
	libro="El Señor de los anillos"
	capitulo="$(echo "$x" | sed -r 's/[0-9]{1,2}-(.*)\.opus/\1/1' | tr "_" " " | sed -r 's/^(.)/\u\1/1')"
	comentario="Hecho con mucho amor. ^_^/  NAD"
	opustags -i "$x" -a album="$libro" -a author="$autor" -a title="$capitulo ($i/$total)" -a chapter="$i" -a artist="$autor" -a comment="$comentario"
	i=$(( $i + 1 ))
done < $1
