#!/bin/sh

#  _
# | |_ __ _  __ _  ___  __ _ _ __
# | __/ _` |/ _` |/ _ \/ _` | '__|
# | || (_| | (_| |  __/ (_| | |
#  \__\__,_|\__, |\___|\__,_|_|
#           |___/

i=0
total=$(cat $1 | wc -l)
	autor="JRR Tolkien"
	libro="La caída de Arturo"
	comentario="Hecho con mucho amor. ^_^/  NAD"
while read -r archivo
do

	capitulo="$(echo "$archivo" | sed -r 's/[0-9]{1,2}-(.*)\..*/\1/1' | tr "_" " " | sed -r 's/^(.)/\u\1/1')"

	#opustags -i "$archivo" -a album="$libro" -a author="$autor" -a title="$capitulo ($i/$total)" -a booktitle="$libro" -a chapter="$i" -a artist="$autor" -a comment="$comentario"

	#i=$(( $i + 1 ))

	## Para modificar una tag
	opustags -i "$archivo" --set title="$capitulo"

	## Para borrar una tag
	#opustags -i "$archivo" -d encoder

done < $1
