#!/bin/bash

# Toggles rfkill bluetooth and wifi
# just to save some battery.

FG_RED=$(tput setaf 1)
RED='\033[0;31m'
NC=$(tput sgr0)
FMT_RESET="\033[0m"
FG_GREEN="\e[32m"

wifiStatus="$(/usr/bin/rfkill | awk '/3 wlan/ { print $4 }')"
blStatus="$(/usr/bin/rfkill | awk '/2 bluetooth/ { print $4 }')"

echo -e "Wifi: $wifiStatus\nbl: $blStatus"

select choice in Wifi Bluetooth "${FG_RED}Both${NC}" "exit"
do
	case $choice in
		Wifi) rfkill toggle 3 && break;;
		Bluetooth) rfkill toggle 2 && break;;
		"${FG_RED}Both${NC}") rfkill toggle 2 3 && break;;
		"exit") echo -e "${FG_GREEN}Sin cambios${FMT_RESET}" && exit 0;;
	esac
done

echo -e "Done ${RED}✔${FMT_RESET}"
