#!/bin/sh
#
# ( Last Update: 2023-08-31)
#

target_dir="$HOME/celular"

mount_cel () {
  mkdir -p "$target_dir";
  aft-mtp-mount "$target_dir";
};

unmount_cel () {
  fusermount -u "$target_dir" &&
  rmdir "$target_dir";
}

choice=$(printf '%s\n%s' "Mount" "Unmount" |\
  dmenu -p "Elegí" -fn "$dmenu_font")

case $choice in
  Mount) mount_cel;;
  Unmount) unmount_cel;;
esac
