#!/bin/sh

#            _                               _        _
#  _   _ ___| |__   __ _ _   _  __ _ _ __ __| |    __| |_ __ ___   ___ _ __  _   _
# | | | / __| '_ \ / _` | | | |/ _` | '__/ _` |   / _` | '_ ` _ \ / _ \ '_ \| | | |
# | |_| \__ \ |_) | (_| | |_| | (_| | | | (_| |  | (_| | | | | | |  __/ | | | |_| |
#  \__,_|___/_.__/ \__, |\__,_|\__,_|_|  \__,_|___\__,_|_| |_| |_|\___|_| |_|\__,_|
#                  |___/                     |_____|

# Dmenu for handling usbguard cli most basic commands


options=$(echo -e "List\nAllow\nBlock\nAdd\nErase" | dmenu -p "Usbguard: ")

case $options in
	List) usbguard list-devices;;
	Allow) usbguard list-devices | grep -i "block" | dmenu -i -l 35 ;;
	Block);;
	Add);;
	Erase);;
esac
