#!/bin/sh

# Saca una foto con la webcam y la guarda en $TARGEBASE/$TIMESTAMP
# Muestra una notificación y hace un ruido de shutter

# Variables:
TIMESTAMP="webcam_shot-$(date "+%d-%m-%Y-%H:%M").jpg"
TARGETBASE="/data/pictures/webcam";
[ ! -d $TARGETBASE ] && mkdir -p $TARGETBASE ;
SHUTTER="/data/music/sounds/shutter.mp3"


setsid -f ffmpeg -f video4linux2 -s 1024x786 -i /dev/video0 -ss 0:0:2 -frames 1 "$TARGETBASE/$TIMESTAMP" &
sleep 1
[ ! -z "$SHUTTER" ] && \mpv --msg-level=all=no $SHUTTER &
action=$(dunstify -t 10000 --action="dragon,picture" "📸 WebCam-shot guardada en:" "$TARGETBASE/$TIMESTAMP")
case $action in
	"dragon") dragon -x "$TARGETBASE/$TIMESTAMP";;
esac
