#!/bin/sh

#  _            _                      _ _     _           _      __       _
# | |__   __ _ (_) __ _ _ __  ___ __ _| (_) __| | __ _  __| |    / _| ___ | |_ ___
# | '_ \ / _` || |/ _` | '__|/ __/ _` | | |/ _` |/ _` |/ _` |   | |_ / _ \| __/ _ \
# | |_) | (_| || | (_| | |  | (_| (_| | | | (_| | (_| | (_| |   |  _| (_) | || (_) |
# |_.__/ \__,_|/ |\__,_|_|___\___\__,_|_|_|\__,_|\__,_|\__,_|___|_|  \___/ \__\___/
#            |__/       |_____|                            |_____|

# Bajo la calidad de la foto con un comando de verga

input="$1"
out="$(echo $1 | sed -r 's/(.*)\.(.{3,4})/\1-lq\.\2/g')"
convert $input -resize 1024 -sampling-factor 4:2:0 -strip -quality 100 -interlace Plane -gaussian-blur 0.05 -colorspace RGB $out


