#!/bin/sh

#  _            _                      _ _     _           _         _     _
# | |__   __ _ (_) __ _ _ __  ___ __ _| (_) __| | __ _  __| | __   _(_) __| | ___  ___
# | '_ \ / _` || |/ _` | '__|/ __/ _` | | |/ _` |/ _` |/ _` | \ \ / / |/ _` |/ _ \/ _ \
# | |_) | (_| || | (_| | |  | (_| (_| | | | (_| | (_| | (_| |  \ V /| | (_| |  __/ (_) |
# |_.__/ \__,_|/ |\__,_|_|___\___\__,_|_|_|\__,_|\__,_|\__,_|___\_/ |_|\__,_|\___|\___/
#            |__/       |_____|                            |_____|

# Bajo la calidad del video

input="$1"
output="$(basename -a -s .mp4 "$1")-lq.mp4"
select choice in 'Baja' 'Media' 'Alta'
do
case $choice in
	"Baja") calidad=33 && break
		;;
		"Media") calidad=28 && break
			;;
		"Alta") calidad=23 && break
			;;
	esac
done

ffmpeg -loglevel 24 -i $input -vcodec libx264 -profile:v baseline -level 3.0 -c:a aac -pix_fmt yuv420p -crf "$calidad" $output
