#!/bin/sh

#
#   ___ __ _ _ __ ___   ___ _ __ __ _
#  / __/ _` | '_ ` _ \ / _ \ '__/ _` |
# | (_| (_| | | | | | |  __/ | | (_| |
#  \___\__,_|_| |_| |_|\___|_|  \__,_|
#

# facilita el pasaje de las fotos de la camara a
# la computadora dado que el gphoto2 client es
# bastante verga

# Chequear que la cámara esté enchufada
estado=$(gphoto2 --auto-detect | tail -1)
while [ $(echo ${estado:0:1}) = '-' ]
do
dunstify -r 12 -u low "La cámara está apagada" "Reintentar en 4 segundos"
sleep 1
dunstify -r 12 -u low "La cámara está apagada" "Reintentar en 3 segundos"
sleep 1
dunstify -r 12 -u low "La cámara está apagada" "Reintentar en 2 segundos"
sleep 1
dunstify -r 12 -u low "La cámara está apagada" "Reintentar en 1 segundos"
sleep 1
estado=$(gphoto2 --auto-detect | tail -1)
done

# Nombre del archivo en la camara es el input
input="$1"
[ "$(echo ${1:0:6})" = "thumb_" ] && input=$(echo $1 | sed 's/thumb_//g')


# Bajo el archivo a la compu con:
gphoto2 -p $(gphoto2 -L | grep "$input" | cut -d" " -f1 | tr -d "#")

# Si la extensión en CR2, ofrecer transformar a jpeg
if [ "$(echo $input | cut -d"." -f2)" = "CR2" ]
then
	choice=$(echo -e "Sí\nNo" | dmenu -fn "$dmenu_font" -p "¿ Pasar cr2->jpg ?")
	case $choice in
		"Sí") mogrify -format jpg "$input" && notify-send "Se creó:" "$(echo $input | sed 's/CR2/jpg/1')" && rm "$input"
			;;
		"No") notify-send "Se creó:" "$(echo $input)"
			;;
	esac
fi
