#!/bin/sh

# Toma 2 archivos de video, los "mergea" con el
# ffmpeg. Devuelve el archivo en $3
# no va a funcionar si el size de los videos no es el mismo en ese caso usar para convertirlos al mismo tamaño:
#ffmpeg -i IN -vf "scale=1080x1920:force_original_aspect_ratio=decrease,pad=1080:1920:-1:-1:color=black" output.mp4

usage="$(basename "$0") [-h] -- Para juntar dos videos en un solo archivo.
Toma 3 argumentos en total
where:
	-h show this help
Ejemplo: cat_videos ${RED}IN_1.mp4 IN_2.mp4 ${BLUE}OUT.mp4${NORMAL}"

while getopts ':h' option; do
	case "$option" in
		h) echo "$usage"
			exit
			;;
		:) printf "missing argument for -%s\n" "$OPTARG" >&2
			echo "$usage" >&2
			exit 1
			;;
		\?) printf "invalid option: -%s\n" "$OPTARG" >&2
			echo "$usage" >&2
			exit 1
			;;
	esac
done

shift $((OPTIND - 1))

ffmpeg -vsync 0 -i "$1" -i "$2" -filter_complex "[0:v] [0:a] [1:v] [1:a] concat=n=2:v=1:a=1 [v] [a]" -map "[v]" -map "[a]" "$3"

echo "${GREEN}Done ✔${NORMAL}"

ls -lh $1 $2 $3

echo "¿${RED}Borrar${NORMAL} "$1" y "$2" ?"
select choice in 'Sí' 'No'
do
	case $choice in
		'Sí') rm $1 $2 && break;;
		'No') echo "No se borraron" && break;;
	esac
done

echo "${RED}Done ✔${NORMAL}"
echo "bye ${CYAN}👋${NORMAL}"
