#!/bin/sh

#                                             _     _
#   ___ _ __ ___  _ __   ___  __ _ _ ____   _(_) __| | ___  ___  ___
#  / __| '__/ _ \| '_ \ / _ \/ _` | '__\ \ / / |/ _` |/ _ \/ _ \/ __|
# | (__| | | (_) | |_) |  __/ (_| | |   \ V /| | (_| |  __/ (_) \__ \
#  \___|_|  \___/| .__/ \___|\__,_|_|____\_/ |_|\__,_|\___|\___/|___/
#                |_|               |_____|

# Cropea videos
# Le doy un archivo en $1 da opciones sobre como cropear y el output también
# se elige dentro del script.

# Declaro input
input="$1"
video_end="$(ffmpeg -i "$1" 2>&1 | grep Duration | cut -d" " -f4 | tr -d ,)"
# Selecciona como cropear
select choice in "Tiempo inicial --> Delta de tiempo" "Tiempo inicial --> Tiempo final"
do
	case $choice in
		"Tiempo inicial --> Delta de tiempo") t_to="-t" ;
			{ read -e -p "Tiempo inicial ${RED}(00:00:00)${NORMAL}: " ti
			[ ! $ti = "" ] || ti="00:00";
			echo "Tiempo inicial = ${RED}$ti${NORMAL}"
			read -e -p "Delta de tiempo (s): " time
			echo "Delta de tiempo = ${RED}$time${NORMAL}" ; } && break
			;;
		"Tiempo inicial --> Tiempo final")
			t_to="-to"
			{ read -e -p "Tiempo inicial ${RED}(00:00:00)${NORMAL}: " ti
			[ ! $ti = "" ] || ti="00:00";
			echo "Tiempo inicial = ${RED}$ti${NORMAL}"
			read -e -p "Tiempo final ("$video_end"): " time
			[ ! $time = "" ] || time="$video_end";
			echo "Tiempo final = ${RED}$time${NORMAL}" ; } && break
			;;
	esac
done

# Declaro el nombre del archivo final de una forma medio chota.
output="crop-"$(date "+%d%m-%H%M")".mp4"
read -e -p "${GREEN}Nombre del output [${RED}$output${NORMAL}]: " out
if [ ! -z $out ]
then
[ "$(echo "${out: -4}")" = ".mp4" ] || out="$out.mp4"; output=$out
fi

echo -e "${RED}Cropeando...${NORMAL}"

ffmpeg -loglevel 24 -i $input -ss "$ti" "$t_to" $time $output

# Si hubo error corto el programa
[ $? = 0 ] || { echo "Hubo un error" && exit 0; }

echo "¿${RED}Sharearbilizar${NORMAL} $output?"
select choice in 'Sí' 'No'
do
	case $choice in
		'Sí') shareabilizar_video $output && break
			;;
		*) break
			;;
	esac
done

echo "${RED}Done ✔${NORMAL}"
echo "bye ${CYAN}👋${NORMAL}"
