#!/bin/sh

#            _        _               _     _
#  _ __ ___ | |_ __ _| |_ ___  __   _(_) __| | ___  ___
# | '__/ _ \| __/ _` | __/ _ \ \ \ / / |/ _` |/ _ \/ _ \
# | | | (_) | || (_| | ||  __/  \ V /| | (_| |  __/ (_) |
# |_|  \___/ \__\__,_|\__\___|___\_/ |_|\__,_|\___|\___/
#                           |_____|

# Rota el video
icon1="↪"
icon2="↩"

file_in="$1"
file_out="$(echo "$file_in" | sed 's/\(\..\{3,4\}\)/-rotated\1/1')"
select choice in "Clockwise $icon2" "Counterclock $icon1" "exit"
do
	case $choice in
		"Clockwise $icon2")  ffmpeg -loglevel 0 -i "$file_in" -vf transpose=1 "$file_out"&& break;;
		"Counterclock $icon1") ffmpeg -loglevel 0 -i "$file_in" -vf transpose=2 "$file_out" && break;;
		"exit") echo "${GREEN}Sin cambios${NORMAL}" && exit 0;;
	esac
done
