#!/usr/bin/env bash

# TR_APP_VERSION --> 3.00
# TR_TIME_LOCALTIME --> Tue Jun 23 13:38:25 2020
# TR_TORRENT_DIR --> /data/torrents/torrent_files/
# TR_TORRENT_HASH --> 4a52e9f73ba3032fbc5da46f7b89302c741352c
# TR_TORRENT_ID --> 8
# TR_TORRENT_NAME --> primer directorio sin root  "Avenger (2000)"

icon="🎞"
icon2="📕"

SOUND="/data/music/sounds/beep.mp3"
[ -e $SOUND ] && \mpv --quiet --no-terminal "$SOUND";

notify-send -t 10000 "Torrent Done:" "$TR_TORRENT_NAME" 2> $LOGS/torrentdone.log ;

is_movie () {
# Si es una película, la manda a la carpta de películas e intenta bajar subtítulo
([ -d "/data/peliculas" ] && dir_pelis="/data/peliculas") || exit 1;
peli="$(find "$TR_TORRENT_DIR$TR_TORRENT_NAME" -name "*.mp4" -o -name "*.mkv" -o -name "*.avi")"
	if [ -f "$peli" ];
	then
		transmission-remote -t "$TR_TORRENT_ID" --move "$dir_pelis" &> /dev/null && notify-send "$icon $TR_TORRENT_NAME" "$icon  --> $dir_pelis  ";
		sleep 5s;

    basename_peli=$(basename $peli);
		[ -e "$dir_pelis}/${TR_TORRENT_NAME}${basename_peli}" ];
    else
		notify-send "no funcó" && exit 1;
	fi
}

is_movie

case $TR_TORRENT_NAME in
	*epub|*mobi|*pdf) transmission-remote -t "$TR_TORRENT_ID" --move "/data/downloads" &> /dev/null && notify-send "$icon2 $TR_TORRENT_NAME" "$icon2 -->> /data/downloads"
		;;
esac
