#!/bin/sh
#
# TODO: Borrar ese torrentdone y el comando del transmission comentado la próxima vez que entre acá.
# Llamo a ese script desde la config file y no desde el comando (26/9/20)
#
TORRENTDONE="$HOME_LOCAL/scripts/torrent/torrentdone"

pgrep -x transmission-da > /dev/null || (transmission-daemon -c /data/torrents && notify-send "Starting transmission daemon.." && sleep 3)
#transmission-remote -a "$@" --torrent-done-script $TORRENTDONE && notify-send "Torrent added"
transmission-remote -a "$@" && notify-send "Torrent added"
