#!/bin/sh

# Script que usa el dmenu
# PARA TERMINAR LA SESION O APAGAR LA COMPU

FUENTE="monospace 16"


# Prompt options to select
FIRST_CHOICE=`echo -e "Restart dwmbar\nRestart dwm\nKill xinit" | dmenu -fn "$FUENTE" -i -p "¿Qué querés hacer?"`

#
case $FIRST_CHOICE in
	"Restart dwmbar") restart_dwmbar;;
	"Restart dwm") /usr/bin/killall dwm;;
	"Kill xinit") /usr/bin/killall xinit;;
esac
