#!/bin/sh

#            _       _                                       _
#  _ __ ___ | | ____| | ___   ___ _   _ _ __ ___   ___ _ __ | |_
# | '_ ` _ \| |/ / _` |/ _ \ / __| | | | '_ ` _ \ / _ \ '_ \| __|
# | | | | | |   < (_| | (_) | (__| |_| | | | | | |  __/ | | | |_
# |_| |_| |_|_|\_\__,_|\___/ \___|\__,_|_| |_| |_|\___|_| |_|\__|
#

# Genera un archivo con un mini template para latex

nombre_final="$1"

while [ -z "$nombre_final" ]
do
	read -p "Nombre para archivo: " nombre_final
done

[ "$(echo $nombre_final | rev | cut -d. -f1 | rev)" = "tex" ] || nombre_final="${nombre_final}.tex"
if [ ! -z "$nombre_final" ] && [ ! -e "$nombre_final" ]
then
	echo '\documentclass[12pt,a4paper,oneside,draft]{report}
% Sacar draft para que aparezcan las imagenes.
% Opciones: 10pt, 11pt, landscape, twocolumn, fleqn, leqno...
% Opciones de clase: article, report, letter, beamer...

% Paquetes:
% =========
\usepackage[utf8]{inputenc}  % Para poder escribir con tildes en el editor.
\usepackage[spanish,english]{babel}  % Para cortar las palabras en silabas, creo.
\usepackage[ddmmyyyy]{datetime}
\usepackage{amsmath}  % Soporte de mathmatics
\usepackage{amssymb}  % fuentes de mathmatics
\usepackage{array}  % Para tablas y eso
\usepackage{caption} % Configuracion de figuras y tablas
\usepackage{xcolor} % Para colorear el texto: black, blue, brown, cyan, darkgray, gray, green, lightgray, lime, magenta, olive, orange, pink, purple, red, teal, violet, white, yellow.
\usepackage{graphicx} % Necesario para poner imagenes

% Definiciones:
% =============

\begin{document}

% Datos de importancia
\title{TITULO}
\author{NOMBRE AUTOR}
\date{\today} % Cambiar de ser necesario

ACA VA EL TEXTO <++>

\end{document}

% Ejemplos:
% text color --> {\color{violet} texto violeta}
% color boxed text --> \colorbox{violet}{texto con fondo violeta}
% color framed text --> \fcolorbox{violet}{white}{texto enmarcado violeta}
% IMAGENES --> \includegraphics[width=0.5\textwidth]{ARCHIVO}' >> "$nombre_final"


nvim "$nombre_final"


else
	echo -e "¡Error! Falta nombre de archivo o el nombre ingresado ya existe:\n\"$RED"$nombre_final"$NORMAL\"" && exit 0
fi
