#!/bin/sh

#            _       _                                       _
#  _ __ ___ | | ____| | ___   ___ _   _ _ __ ___   ___ _ __ | |_
# | '_ ` _ \| |/ / _` |/ _ \ / __| | | | '_ ` _ \ / _ \ '_ \| __|
# | | | | | |   < (_| | (_) | (__| |_| | | | | | |  __/ | | | |_
# |_| |_| |_|_|\_\__,_|\___/ \___|\__,_|_| |_| |_|\___|_| |_|\__|
#

# Genera un archivo con un mini template para latex


nombre_final="$1"
directorio_templates="$HOME_LOCAL/scripts/templates/latex"

while [ -z "$nombre_final" ]
do
	read -e -p "Nombre para archivo: " nombre_final
done

[ "$(echo $nombre_final | rev | cut -d. -f1 | rev)" = "tex" ] || nombre_final="${nombre_final}.tex"
if [ ! -z "$nombre_final" ] && [ ! -e "$nombre_final" ]
then
 select choice in "Documento normal" "Carta" "CIENCIA" "Cancelar"
 do
	 case $choice in
		 "Documento normal") cat "$directorio_templates/document_latex_template" > $nombre_final && break
			 ;;
		 "Carta") cat "$directorio_templates/carta_latex_template" > $nombre_final && break
			 ;;
		 "Ciencia") cat "$directorio_templates/ciencia_latex_template" > $nombre_final && break
			 ;;
		 "Cancelar") echo "No se hizo nada" && exit 0
			 ;;
	 esac
 done
nvim "$nombre_final"
else
	echo -e "¡Error! Falta nombre de archivo o el nombre ingresado ya existe:\n\"$RED"$nombre_final"$NORMAL\"" && exit 0
fi
