#!/bin/sh

# Shows the price for desired cryptocurrencies. Module updates automatically
# every calendar day, but can also be updated with a middle click.

# Currencies should be ;-separated:
# human-readable name;urlname;icon
coins="Bitcoin;btc;💰
EOSIO;eos;🍸
NZD;nzd;🇳🇿"

# Directory where currency info is stored.
dir="${XDG_DATA_HOME:-$HOME/.local/share}/crypto-prices"

# Para acortar los números no significativos.
formatPrice () {
	digitos="$(echo $1 | cut -d"." -f1 | wc -c)"
	if [ "$digitos" -ge 4 ];
	then
		printf "%.0f" "$1"
	else
		printf "%.2f" "$1"
	fi
}

getprices() { # The command to get the desired prices
	printf "🔃 "; printprices
	{ rm -rf "${dir:?}/*"
	echo "$coins" | while IFS=';' read -r human web icon; do
	val="$(curl -s "rate.sx/1$web")" &&
	valBar="$(formatPrice "$val")" &&
		echo "$icon;$valBar;$val;$human;" > "$dir/$web"
	done;
	[ -d "$dir" ] && touch "$dir"
	pkill -RTMIN+13 "${STATUSBAR:-dwmblocks}" ;} &
	exit
	}

printprices() { # Print/format all prices
	for x in "$dir"/*; do
		[ -f "$x" ] || break
		info="$(cut -d';' -f-2 --output-delimiter=':' "$x")"
		#info="$(cut -d';' -f-2 "$x")"
		printf "%s " "$info"
	done | sed 's/ $/\n/'
	}

[ ! -d "$dir" ] && mkdir -p "$dir" && { getprices; exit ;}

# If currencies haven't been updated today, try to update them.
[ "$(stat -c %x "$HOME/.local/share/crypto-prices" | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
	{ ping -q -c 1 1.1.1.1 >/dev/null 2>&1 && getprices || exit ;}

case $BUTTON in
	1) uptime="$(date -d "$(stat -c %x "$dir")" '+%D at %T' | sed "s|$(date '+%D')|Today|")"
		notify-send -t 15000 "Exact prices in USD" "$(awk -F';' '{print $1, $4 ":\n$" $3}' "$dir"/*)
<b>Last updated:</b>
$uptime" ;;
	2) getprices ;;
	3) notify-send "💸 Crypto-currency module" "\- Left click for exact prices.
- Middle click to update.
- Shows 🔃 if updating prices.
- Manually add/remove currencies to list in the script." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

printprices
