#!/bin/sh
icon="📅:"
# Creo el archivo con el calendario
calendar="${XDG_DATA_HOME:-$HOME/.local/share}/calendar"

getCalendar () {
# Calendario anual, lunes primer día.
# se muestra en color el día actual.
	{
	LANG=es_AR.UTF-8 \cal -y -m --color=always > "$calendar"
	if [ -e "$calendar" ];then
		sed -i "s/.*\([ 123][0-9].*\)27m/${NORMAL}${BOLD}${RED}\1${NORMAL}${NORMAL}/g" $calendar
		sed -i "s/\([a-z][a-z][a-z]\+\)/${NORMAL}\1${NORMAL}${NORMAL}/g" $calendar
		sed -i "s/\($(LANG=es_AR.UTF-8 date "+%B")\)/${NORMAL}${BOLD}${RED}\1${NORMAL}${NORMAL}/g" $calendar
	fi
}
pkill -RTMIN+9 dwmblocks; exit
}

[ ! -e "$calendar" ] && getCalendar
[ "$(stat -c %x "$calendar" | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] && \
	{ getCalendar || exit ;}

case $BUTTON in
	1) setsid -f falacritty -d 66 36 -e less -Srf "$calendar";;
	3) setsid -f falacritty -d 140 36 -e wyrd;;
	2) getCalendar;;
	6) "$TERMINAL" -e "$EDITOR" "$0";;
esac

# Texto para mostrar en la barra
printf "$icon%s " "$(LANG=es_AR.UTF-8 date "+%a%-d/%-m" | sed 's|^\([a-z]*\)|\u\1|1')"
