#!/bin/sh

dwm_mpc () {
	if ps -C mpd > /dev/null; then
		ARTIST=$(mpc current -f %artist%)
		TRACK=$(mpc current -f %title%)
		POSITION=$(mpc status | grep -E "%)" | awk '{ print $4 }' | awk -F/ '{ print $1 }' | tr -d " ")
		DURATION=$(mpc current -f %time%)
		STATUS=$(mpc status | sed -n 2p | awk '{print $1;}')
		[ "$STATUS" = "[playing]" ] &&	printf "%s%s-%s %s%s" "$SEP1" "$ARTIST" "$TRACK" "$POSITION" "$SEP2"
	fi
}

dwm_mpc
