#!/bin/sh


# Change the value of LOCATION to match your city
dwm_weather() {
	LOCATION=wellington
	WEATHERUNI="$(curl -s wttr.in/$LOCATION?format=1 2> $LOGS/weather_error.log)"
	WEATHER="$(echo "$WEATHERUNI" | grep -o "[0-9].*" | tr -d "\n")"
	printf "%s" "$SEP1"
	if [ "$IDENTIFIER" = "unicode" ]; then
		printf "%s" "$WEATHERUNI"
	else
		if [ ${#WEATHER} -lt 10 ]; then
			printf "WEA %s" "$WEATHER"
		else
			printf "WEA %s" "N/A"
		fi
	fi
	printf "%s" "$SEP2"
}

dwm_weather
