#!/bin/sh

BTC=$(printf "%.0f" "$(curl -s rate.sx/1BTC)" )
EOS=$(printf "%.2f" "$(curl -s rate.sx/1EOS)" )
USDNZD=$(printf "%.2f" "$( echo "$(curl -s rate.sx/1NZD)*0.97" | bc -ql )")

printf "%sBTC:%s,EOS:%s,NZD:%s%s" "$SEP1" "$BTC" "$EOS" "$USDNZD" "$SEP2"
