#!/bin/bash

layout=$(ibus engine | cut -d":" -f2)

print_ibus_keyboard () {
icon=""
	case $layout in
		us) printf "%s%s " "$icon" "eng";;
		latam) printf "%s%s " "${icon}" "latam";;
		zh) printf "%s%s " "${icon}" "中文";;
		es) printf "%s%s " "${icon}" "esp";;
	esac
}

ibus_keyboard_toggle () {
    if [[ $layout == "latam" ]] || [[ $layout == "zh" ]]; then
		ibus engine xkb:us::eng
	else
		ibus engine xkb:latam::spa
	fi
	pkill -RTMIN+8 dwmblocks
}

ibus_keyboard_zh () {
	ibus engine m17n:zh:tonepy ;
		pkill -RTMIN+8 dwmblocks
	}

case $BUTTON in
	
	1)ibus_keyboard_toggle;;
	3)ibus_keyboard_zh;;
  2)ibus-setup;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

print_ibus_keyboard
