#!/bin/sh

# Micrófono y Monitor en dwmbar
icon="🎙"

mic_volume="$(pamixer --source 1 --get-volume)%"
case $BUTTON in
	1) pamixer --source 1 -t
		;;
	4) pamixer --source 1 -i 2
		;;
	5) pamixer --source 1 -d 2
		;;
	3) notify-send -t 10000 "$icon Mic module" "Mic Vol: $mic_volume
--------------------------
Shows "-" if muted.
Shows "$icon" if not muted
--------------------------
Left click - Mute toggle"
;;
	6) "$TERMINAL" -e "$EDITOR" "$0"
		;;
esac

mic_muted=$(pamixer --source 1 --get-mute)

if [ $mic_muted = true ]
then
	echo -n "- "
else
	echo -n "$icon:$mic_volume "
fi

