#!/bin/bash

# Micrófono y Monitor en dwmbar
icon=""
icon_mute="" 
mic_volume="$(pamixer --source 5 --get-volume)%"
case $BUTTON in
	1) pamixer --source 5 -t && pkill -RTMIN+17 dwmblocks;
		;;
	4) pamixer --source 5 -i 2 && pkill -RTMIN+17 dwmblocks;
		;;
	5) pamixer --source 5 -d 2 && pkill -RTMIN+17 dwmblocks;
		;;
	3) notify-send -t 10000 "$icon Mic module" "Mic Vol: $mic_volume
--------------------------
Shows "-" if muted.
Shows "$icon" if not muted
--------------------------
Left click - Mute toggle"
;;
	6) "$TERMINAL" -e "$EDITOR" "$0"
		;;
esac

mic_muted=$(pamixer --source 5 --get-mute | tr -d "\n")

if [[ "$mic_muted" == true ]]
then
	printf "%s " "$icon_mute"
else
	printf "%s%s " "$icon" "$mic_volume"
fi
