#!/bin/sh

# Monitor en dwmbar
icon="🎙"

monitor_volume="$(pamixer --source 1 --get-volume)%"
case $BUTTON in
	1) pamixer --source 1 -t
		;;
	4) pamixer --source 1 -i 2
		;;
	5) pamixer --source 1 -d 2
		;;
	3) notify-send -t 10000 "$icon Monitor module" "Monitor Vol: $monitor_volume
--------------------------
Shows "-" if muted.
Shows "$icon" if not muted
--------------------------
Left click - Mute toggle"
;;
	6) "$TERMINAL" -e "$EDITOR" "$0"
		;;
esac

monitor_muted=$(pamixer --source 1 --get-mute)

if [ $monitor_muted = true ]
then
	echo -n "-"
else
	echo -n "$icon:$monitor_volume"
fi

