#!/bin/sh

# Monitor en dwmbar
icon="🎙"

monitor_volume="$(pamixer --source 3 --get-volume)%"
case $BUTTON in
	1) pamixer --source 3 -t && pkill -RTMIN+6 dwmblocks
		;;
	4) pamixer --source 3 -i 2 && pkill -RTMIN+6 dwmblocks
		;;
	5) pamixer --source 3 -d 2 && pkill -RTMIN+6 dwmblocks
		;;
	3) notify-send -t 10000 "$icon Monitor module" "Monitor Vol: $monitor_volume
--------------------------
Shows "-" if muted.
Shows "$icon" if not muted
--------------------------
Left click - Mute toggle"
;;
	6) "$TERMINAL" -e "$EDITOR" "$0"
		;;
esac

monitor_muted=$(pamixer --source 3 --get-mute)

if [ $monitor_muted = true ]
then
	echo -n "-" | tr -d " " | tr -d "\n"
else
	echo -n "$icon:$monitor_volume" | tr -d " " | tr -d "\n"
fi

