#!/bin/bash

# Monitor en dwmbar
icon=""
icon_mute="" 

command(){
  pamixer --source 3 "$1";
}
killCommand(){
  pkill -RTMIN+18 dwmblocks;
}

monitor_volume="$(command --get-volume)%"

monitor_muted=$(command --get-mute | tr -d "\n")

if [ "$monitor_muted" == "true" ]
then
	printf "%s" "$icon_mute"
else
	printf "%s%s " "$icon" "$monitor_volume"
fi

case $BUTTON in
	1) command -t && killCommand;;
	4) command -i 2 && killCommand;;
	5) command -d 2 && killCommand;;
	6) "$TERMINAL" -e "$EDITOR" "$0";;
esac
