#!/bin/sh
#
icon="󰋋"
icon2='󰟎'

musicOn () {
    if [ "$STATUS" = "[playing]" ]; then
        printf "%s" " $icon  " | tr -d "\n"
    else
        printf "%s" "$icon2 " | tr -d "\n"
    fi
}

dancingMan() {
    STATUS=$(mpc status | sed -n 2p | awk '{print $1;}')
    if [ "$STATUS" = "[playing]" ]; then
        if [ $(($1 % 2)) -eq 0 ]; then
            echo -e "   ♪╔(・o･)╝♪♫  ♩♩♫~(◠o◠)~♫\n======================================"
        else
            echo -e " ♫♪ ╚(･o・)╗ ♪  ♩~(◠0◠)~♫ ♩♫\n======================================"
        fi
    fi
}

notifyInfo() {
    local -i i=8
    local ARTIST TRACK REPEAT SH NEXT NOW

    while [ $i -gt 0 ]; do
        ARTIST=$(mpc current -f %artist%)
        TRACK=$(mpc current -f %title%)
        REPEAT=$(mpc status %repeat%)
        SH=$(mpc status %random%)
        NEXT=$(mpc queued)
        read NOW <<< $(mpc status | awk '/^\[/ { printf $3 "\t" $4}')
        dunstify -r 213 -t 1500 "🎶$ARTIST
  $TRACK " " $NOW
$(dancingMan $i)
Next song: $NEXT
 ======================================
        random: "$SH"   repeat: "$REPEAT""
        sleep 0.8
        ((i--))
    done
}


STATUS=$(mpc status | sed -n 2p | awk '{print $1;}')

case $BUTTON in
        3) (notifyInfo &> /dev/null) & ;;
    1) mpc -q toggle && pkill -RTMIN+1 dwmblocks ;;
    4) [ "$STATUS" = "[playing]" ] && mpc -q next ;;
    5) [ "$STATUS" = "[playing]" ] && mpc -q prev ;;
    2) (setsid -f falacritty -o window.dimensions.columns=150 -o window.dimensions.lines=30 -e ncmpcpp &> /dev/null) & ;;
    6) (setsid -f "$TERMINAL" -e "$EDITOR" "$0" &> /dev/null) & ;;
    7) mpc_dmenu ;;
esac

# Status bar
musicOn
