#!/bin/sh
icon="🎧"

musicOn () {
	if [ "$STATUS" = "[playing]" ]; then
		i=$(date "+%S")
		if [ $(expr $i % 3 ) -eq 0 ]; then
			echo -n " (🎶♫$icon♫🎶) "
		else
			echo -n "((♫🎶$icon🎶♫))"
		fi
	else
		echo -n "$icon "
	fi
}

dancingMan () {
	# Dancing in its purest form.
	if [ $(expr $1 % 2 ) -eq 0 ]; then
		parallel echo ::: "   ♪╔(・o･)╝♪♫  ♩♩♫~(◠o◠)~♫ " "======================================"

	else
		parallel echo ::: " ♫♪ ╚(･o・)╗ ♪  ♩~(◠0◠)~♫ ♩♫" "--------------------------------------"
	fi
}

notifyInfo () {
	i=8
	while [ $i -gt 0 ];do
		read now <<< $(mpc status | awk '/^\[/ { printf $3 "\t" $4}')
		dunstify -r 213 -t 1000  "🎶$ARTIST
$TRACK" "  $now
	$(dancingMan $i)
Next song: $NEXT "
let i=$(echo "$i-1" | bc -ql) > /dev/null
	 sleep 1;
	done
}

ARTIST=$(mpc current -f %artist%)
TRACK=$(mpc current -f %title%)
STATUS=$(mpc status | sed -n 2p | awk '{print $1;}')
NEXT=$(mpc queued)

case $BUTTON in
	3) notifyInfo;;
	1) mpc toggle > /dev/null;;
	4) mpc next   > /dev/null;;
	5) mpc prev   > /dev/null;;
	2) setsid -f falacritty -d 130 30 -e ncmpcpp;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0";;
	7) mpc_dmenu;;
esac

musicOn
