#!/bin/sh

# Porcentaje de RAM usada
read tot used <<< $(\free | awk '/Mem/ { printf $2" "$3 "\n"}')
MEM=$(echo $used/$tot*100 | bc -l)

# CPUs Load
CPUS=$(lscpu | awk '/^CPU\(s\)/ { print $2 }' | head -1)
LOAD=$(uptime | grep -oE "[0-9]{1}\.[0-9]{2}" | head -1)
CPU=$(echo $LOAD/$CPUS*100 | bc -l)

# CPU temperature
TEMP=$(sensors | grep Package | cut -d" " -f5 | sed 's|\+\(.*\)\.[0-9]\(.\)C$|\1\2|')

printf "💻:%.0f%%,%s,%.0f%% " "$CPU" "$TEMP" "$MEM" | sed 's|\n$||g';

case $BUTTON in
	1) setsid -f falacritty -o window.dimensions.columns=80 -o window.dimensions.lines=35 -e top -d 8 -u $(id -u);;
	2) pkill -RTMIN+3 dwmblocks ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
