#!/bin/sh

# Porcentaje de RAM usada
read tot used <<< $(\free | awk '/Mem/ { printf $2" "$3 "\n"}')
MEM=$(echo $used/$tot*100 | bc -l)

# CPU temperature
TEMP=$(sensors | grep edge | cut -d" " -f10 | sed 's|\+\(.*\)\.[0-9]\(.\)C$|\1\2|')

# CPUs Load
CPUS=$(lscpu | awk '/^CPU\(s\)/ { print $2 }')
LOAD=$(uptime | grep -oE "[0-9]{1}\.[0-9]{2}" | head -1)
CPU=$(echo $LOAD/$CPUS*100 | bc -l)

# Used and total storage in /home (rounded to 1024B)
HOME_USED=$(\du -chs --exclude="*.pyc" "$HOME" /data | cut -f1 | tail -1)
printf "ram:%.0f%% 💻:%.0f%%,%s 💽:%s " "$MEM" "$CPU" "$TEMP" "$HOME_USED"

case $BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
