#!/bin/sh

# Used and total storage in /home (rounded to 1024B)
USED=$(\du -chs --exclude="*.pyc" --exclude="$HOME/.local/cache/yay/*" "$HOME" /data | cut -f1 | tail -1)
icon="💾"
icon2="💽"

getSizes () {
echo -e "Data:
$(parallel \du -hs --exclude=""*.pyc"" --exclude="$HOME" '{}' ::: $(\du -h /data -d 1 | head -n -2 | cut -f2 | tr '\n' ' ') | head -n -1 | sort -rh)
-------------------
Home:
$(\du -hs --exclude *.pyc ~)
-------------------
System:
$(\du -hs --exclude *.pyc --exclude /home/* --exclude /data --exclude /media --exclude /proc / 2> /dev/null)"
}

lsSizes () {
	notify-send -t 0 "$icon2 Local Storage:" "$(getSizes)"
}

case $BUTTON in
	3) setsid -f falacritty -o window.dimensions.columns=100 -o window.dimensions.lines=35  -e lf  ;;
	1) pkill -RTMIN+4 dwmblocks && setsid -f falacritty -o window.dimensions.columns=100 -o window.dimensions.lines=35  -e \ncdu --color dark / ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

printf "$icon:%s " "$USED"

#$(\du -hs --exclude *.pyc --exclude /home $(\du -h /data -d 1 | head -n -2 | cut -f2 | tr '\n' ' ') | head -n -1 | sort -rh)
