#!/bin/bash

# Da la hora y tiene
# también horarios y temperaturas
# internacionales

clock_icon="󰥔"

dir="$HOME/.local/share/cities"
[ ! -d "$dir" ] && mkdir -p "$dir"

ciudades="America/Argentina/Buenos_Aires;BuenosAires;CABA;🇦🇷
America/New_York;NewYork;NYC;🇺🇸
Europe/Madrid;Barcelona;Barcelona;🇪🇸
NZ;Auckland;Auckland;🇳🇿"


# Update interval in seconds
update_interval=3600 

# If there is inet and the files are older than "update_interval"
# then returs true ... or similar #bash
areFilesOld () {
  ping -q -c 1 1.1.1.1 > /dev/null && \
    (( $(date "+%s") - $(stat -c %Y "$dir"/*temperature | head -1) >\
    $update_interval ))
}

# Prints temperature to $2
getTemp() {
    curl -sf "wttr.in/$1?format=%f\(%t\)" > "$2"
}

# Update depending on "areFilesOld" result the .temperature files
updateTemp() {
  if areFilesOld; then
        echo "$ciudades" |
        while IFS=';' read -r tz location human icon
        do
            getTemp "${location}" "$dir/${location}.temperature"
        done
    fi
}

# gets the time in the tz=$1
getTime () {
    TZ="$1" LANG=es_AR.UTF-8 date "+%A %_H:%M" | sed 's|^\(.\)|\u\1|1';
}

print() {
    updateTemp; #update temp if necessary
    echo "$ciudades" |
    while IFS=';' read -r tz location human icon
    do
        time=$(getTime "$tz");
        temp="$(cat "$dir/${location}.temperature")";
        echo -e "$icon <b>$human</b>\n$time  $temp" > "$dir/$location";
    done
    dunstify -r 1 -t 10000 "Otros Horarios:" "$(cat $(find "$dir" -type f ! -name "*.temperature"))"
}

case $BUTTON in
    1) print
      ;;
    6) "$TERMINAL" -e "$EDITOR" "$0"
      ;;
esac

# Texto para mostrar en la barra
printf "$clock_icon%s " "$(date "+%-H:%M")"
