#!/bin/sh

icon="☠"

# Si el transmission está prendido, muestra el icono.
pgrep transmission-da > /dev/null && printf "%s " "$icon"


# Hacer esto:  <25-07-20, nad> #
#toggle_list () {
#setsid -f falacritty -d 140 30 -e watch -d -n 1 -t -c transmission-remote -l;;}


case $BUTTON in
	1) setsid -f falacritty -d 140 30 -e watch -d -n 1 -t -c transmission-remote -l;;
	3) setsid -f torrent_dmenu;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
