#!/bin/bash

case $BUTTON in
    1) setsid -f falacritty -e pulsemixer ;;
    2) pamixer -t ;;
    4) pamixer --allow-boost -i 3 && pkill -RTMIN+6 dwmblocks ;;
    5) pamixer --allow-boost -d 3 && pkill -RTMIN+6 dwmblocks ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ ! "$(pamixer --get-mute)" ] && echo -n "🔇" && pkill -RTMIN+6 dwmblocks && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then icon=""
elif [ "$vol" -lt "30" ]; then icon=""
else icon="";
fi

echo -n "$icon$vol ";
