#!/bin/sh
LOCATION="-36.9267019,175.7895731"

isOldAndIsInet () {
		# Update solo con inet y si el último update son más viejos que la edad objetivo
		showweather;
		ping -q -c 1 1.1.1.1 >/dev/null 2>&1 && {
		[ $(expr $(date "+%s") - $(stat -c %Y "$temp")) -ge 1800 ] && rm $temp ;
		[ $(expr $(date "+%s") - $(stat -c %Y "$weatherreport")) -ge 7200 ] && rm $weatherreport ; }
		}

showweather() {
	printf "%s " "$(sed '16q;d' "$weatherreport" |
		grep -wo "[0-9]*%" | sort -rn | sed "s/^/☔:/g;1q" | tr -d '\n')"
				sed '13q;d' "$weatherreport" | grep -o "m\\([-+]\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{ print "🥶:"$1"°""🌞:"$2"° " }' ;}

getforecast() {
	[ ! -e $weatherreport ] && touch $weatherreport;
		{ [ -z "$(cat $weatherreport)" ] || isOldAndIsInet  ;} &&
			curl -sf "wttr.in/$LOCATION" > "$weatherreport" &&
			uptime="$(LANG=es_AR.UTF-8 date -d "$(stat -c %y "$weatherreport")" '+%A %-d/%-m at %-H:%M' | sed 's|^\([a-z]\{2,\}\)|\u\1|1')" &&
		echo -e "${RED}Last update: ${uptime}${NC}" >> $weatherreport
}

temperaturaActual () {
	[ ! -e $temp ] && touch $temp;
	{ [ -z "$(cat $temp)" ] || isOldAndIsInet ;} &&
	echo -e "<b>Temperatura</b>: $(curl -s wttr.in/${LOCATION}?format=1)" > $temp &&
		uptime="$(LANG=es_AR.UTF-8 date -d "$(stat -c %y "$temp")" '+%A %-d/%-m at %-H:%M' | sed 's|^\([a-z]\{2,\}\)|\u\1|1')" &&
		echo -e "<b>Last update:</b>\n${uptime}" >> $temp ;
		}


weatherreport="${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"
temp="$HOME/.local/share/temp_now"

case $BUTTON in
	3) setsid -f alacritty --class float,term -d 125 42 -e less -Srf "$weatherreport";;
	2) notify-send -t 2000 "⛅ Refreshing..."; temperaturaActual; getforecast ;;
	1) notify-send "🌈 Weather module" "$(cat $temp)";;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0";;
esac

[ ! -e "$weatherreport" ] && touch "$weatherreport" && getforecast
[ ! -e "$temp" ] && touch "$temp"&& temperaturaActual

showweather
