#!/bin/sh

dwm_weather() {
	LOCATION=$1
	WEATHERUNI="$(curl -s wttr.in/$LOCATION?format=1 2> $LOGS/weather_error.log)"
	WEATHER="$(echo "$WEATHERUNI" | grep -o "[0-9].*" | tr -d "\n")"
	if [ ${#WEATHER} -lt 10 ]; then
		printf "%s" "$WEATHER"
	fi
}

BSAS=$(TZ="America/Argentina/Buenos_Aires" LANG=es_AR.UTF-8 date "+%A %_H:%M")hs.
TBSAS=$(dwm_weather BuenosAires &)
BARCELONA=$(TZ="Europe/Madrid" LANG=es_AR.UTF-8 date "+%A %_H:%M")hs.
TBARCELONA=$(dwm_weather Barcelona &)
BUCHAREST=$(TZ="Europe/Bucharest" LANG=es_AR.UTF-8 date "+%A %_H:%M")hs.
TBUCHAREST=$(dwm_weather Bucharest &)


dunstify -t 60000 "$(printf "CABA:\n$BSAS\t$TBSAS
Barcelona: \n$BARCELONA\t$TBARCELONA
Bucarest: \n$BUCHAREST\t$TBUCHAREST")"
