#!/bin/sh

#  _                    _         _                   _                     _
# | |_ ___   __ _  __ _| | ___   | |_ ___  _   _  ___| |__  _ __   __ _  __| |
# | __/ _ \ / _` |/ _` | |/ _ \  | __/ _ \| | | |/ __| '_ \| '_ \ / _` |/ _` |
# | || (_) | (_| | (_| | |  __/  | || (_) | |_| | (__| | | | |_) | (_| | (_| |
#  \__\___/ \__, |\__, |_|\___|___\__\___/ \__,_|\___|_| |_| .__/ \__,_|\__,_|
#           |___/ |___/      |_____|                       |_|

# el nombre lo explica todo. NOTA: Para que el grep funcione, tuve que cancelar un input que también matcheaba en /etc/X11/xorg.input.d/xorg.conf

export LC_ALL=C

TOUCHPAD_ID=$(xinput list | grep "Touchpad" | sed -n -e 's/^.*id=//p'|cut -f1)

if xinput list $TOUCHPAD_ID | grep -q 'This device is disabled'
then
	xinput enable $TOUCHPAD_ID
else
	xinput disable $TOUCHPAD_ID
fi
