#!/bin/sh

#   ____            _
#  / ___|___   ___ | |
# | |   / _ \ / _ \| |
# | |__| (_) | (_) | |
#  \____\___/ \___/|_|
#
#  _____                 _   _
# |  ___|   _ _ __   ___| |_(_) ___  _ __  ___
# | |_ | | | | '_ \ / __| __| |/ _ \| '_ \/ __|
# |  _|| |_| | | | | (__| |_| | (_) | | | \__ \
# |_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
#
#

vf () {
# Abrir un archivo de text usando el fuzzy finder con el $EDITOR
	find $HOME -type f | fzf | xargs -r -I % $EDITOR % && exit;

}

vs(){
# Abrir una sesion de vim usando el fuzzy finder con el $EDITOR
	find $HOME -name "*.vim" | fzf | xargs -r -I % $EDITOR -S % && exit;
}

rvs () {
# REMOVE VIM SWAP FILES
	find $HOME_LOCAL/share/nvim/swap -name "*.swp" | fzf | xargs -r -I % rm % && notify-send "Se eliminó la swap" && exit;
}

superlame () {
# Toma un argumento. Baja el bitrate del mp3 al argumento elegido, para todos
# los archivos del directorio
	arg=${1:-128}
	parallel lame -S --mp3input -b $arg {} {.}.tmp \'&&\' \mv {.}.tmp {} ::: \
		$(find . -maxdepth 1 -name "*.mp3" -exec basename {} \;)
	}

cl() {
	# Change directory and ls
	local dir="$1"
	local dir="${dir:=$HOME}"
	if [[ -d "$dir" ]]; then
		cd "$dir" >/dev/null; ls -ha --color=auto
	else
		echo "bash: cl: $dir: Directory not found"
	fi
}

calc() {
	echo "scale=3;$@" | bc -l
}

ipif() {
	if grep -P "(([1-9]\d{0,2})\.){3}(?2)" <<< "$1"; then
		curl ipinfo.io/"$1"
	else
		ipawk=($(host "$1" | awk '/address/ { print $NF }'))
		curl ipinfo.io/${ipawk[1]}
	fi
	echo
}

qr() {
	# Toma un argumento y lo convierte en un código QR
	arg=$1
	curl qrenco.de/"$arg"
}
