#!/usr/bin/env bash

# PROMPS A DMENU MENU ASKING TO SHUTDOWN

first_choice=`echo -e "Kill X\nReiniciar\nApagar\nPantalla off" | dmenu -fn "$dmenu_font"  -i -p "¿Qué querés hacer?"`

case $first_choice in
	"Reiniciar") systemctl -i reboot
		;;
	"Apagar") systemctl -i poweroff
		;;
	"Kill X") killall xinit
		;;
	"Pantalla off") xset dpms force standby
		;;
esac
