#!/bin/sh


MACADD="$(bluetoothctl list | cut -d" " -f2)"
IS_ON="$(bluetoothctl show "$MACADD" | grep -i powered | cut -d: -f2 | tr -d " ")"
FUENTE="monospace 16"

bl_toggle () {
	if [ "$IS_ON" = "yes" ];
	then
		bluetoothctl power off &&\
		notify-send "Bluetooth off"
	else
		bluetoothctl power on &&\
		notify-send "Bluetooth on"
fi
}

bl_connect () {
	# Prendo el bl si está apagado
	[ "$IS_ON" = "no" ] && bl_toggle

	# Prompt para elegir el device
	CHOICE=$(bluetoothctl devices | cut -d" " -f3- | dmenu -fn "$FUENTE" -i -l 10 -p "¿Cuál?")
	MAC=$(bluetoothctl devices | grep -i "$CHOICE" | cut -d" " -f2 | tr -d " ")
	bluetoothctl connect $MAC && notify-send "Connectado a: " "$CHOICE"

}


FIRST_CHOICE=`echo -e "Toggle\nConnect" | dmenu -fn "$FUENTE" -i -p '¿Qué opción querés?'`

case $FIRST_CHOICE in
	Toggle) bl_toggle 1> /dev/null 2>> $LOGS/bl_dmenu.log
		;;
	Connect) bl_connect 1> /dev/null 2>> $LOGS/bl_dmenu.log
		;;
esac

