#!/bin/sh

#
#   ____      _             _
#  / ___|__ _| | ___     __| |_ __ ___   ___ _ __  _   _
# | |   / _` | |/ __|   / _` | '_ ` _ \ / _ \ '_ \| | | |
# | |__| (_| | | (__   | (_| | | | | | |  __/ | | | |_| |
#  \____\__,_|_|\___|___\__,_|_| |_| |_|\___|_| |_|\__,_|
#                  |_____|
#

EQ="$(echo '' | dmenu -fn $dmenu_font -p "Enter calculation")"
RESULT=$(echo  "scale=3;"$EQ"" | bc -ql)
dunstify -u low -t 10000 "Result: $RESULT"
echo -e "$RESULT" | xclip -r -selection clipboard


