#!/bin/sh

EQ="$(echo '' | dmenu -fn $dmenu_font -p "Enter calculation")"
RESULT=$(echo  "scale=3;"$EQ"" | bc -ql)
dunstify -u low -t 10000 "Result: $RESULT"
echo -e "$RESULT" | xclip -r -selection clipboard
