#!/bin/sh

# Fuente
FUENTE="EmojiOne Color-30"

# File with all the unicode characthers
FILE="$HOME/.local/emoticones/unicode_compilation"

# Old clipboard for comparison with added one
OLD="$(xclip -o -selection clipboard)"

# Opens dmenu ignoring the lines that finish with "#"
# The awk commands can probably be improve
# paste selection to CLIPBOARD
grep -v -e "^#" $FILE | awk -F'   ---   ' '{ printf "%-40s     %s\n", $1, toupper($2) }' |
	dmenu -i -l 20 -fn "$FUENTE" -nb "#000000" -sf "#FFFFFF" -nf "#aaaaaa" |
	awk -F'     ' '{ printf "%s", $1 }' |
	xclip -r -selection clipboard

# If the new chrachter differs from the OLD one
# a pop up will show the charachter copied
NEW="$(xclip -o -selection clipboard)"

if [ ! "$OLD" = "$NEW" ] && [ ! -z "$NEW" ]; then
	pgrep -x dunst && dunstify -r 3214 "Copiado al clipboard:" "$NEW"
fi
