#!/bin/bash

# Macro para spawnear el terminal emulator en floating mode
# Alacritty floating en el medio

confTerminal="$HOME_CONFIG/alacritty/alacritty-floating.yml"

"$TERMINAL" --config-file "$confTerminal" "$@"
