#!/bin/sh

#	 ____                                         _
#	/ ___|  ___ _ __ ___  ___ _ __   ___ __ _ ___| |_
#	\___ \ / __| '__/ _ \/ _ \ '_ \ / __/ _` / __| __|
#	 ___) | (__| | |  __/  __/ | | | (_| (_| \__ \ |_
#	|____/ \___|_|  \___|\___|_| |_|\___\__,_|___/\__|
#

# Screen casting with ffmpeg. This includes capturing audio.
DIRECTORIO="/data/ffmpeg"
FILENAME="$(date '+%d-%m-%y--%H%M')-video"
FORMAT="mkv"
FINAL_NAME="$DIRECTORIO/$FILENAME.$FORMAT"
# ====================

LEFT_SUPERIOR="0,0" # ESQUINA SUPERIOR IZQUIERDA
RESOLUTION="1340x1060" # TAMAÑO DE LA CAPTURA MEDIDO DESDE LEFT_SUPERIOR

# calidad alta con captura de audio hw:0
ffmpeg -f x11grab -video_size 1920x1080 -framerate 60 -i $DISPLAY -f alsa -i pulse:0 -r 30 -s 1920x1080 -c:v libx264 -preset:v veryfast -b:v 2000k -c:a libopus -b:a 96k $FINAL_NAME


# calidad alta con captura de audio hw:0, sección elegida según
# LEFT_SUPERIOR y RESOLUTION
# ffmpeg -f x11grab -framerate 50 -video_size $RESOLUTION -i :0.0+$LEFT_SUPERIOR -f alsa -i pulse -r 30 -b:a 64k $FINAL_NAME

# Captura audio del micrófono y de hw:0.
# RESOLUTION y LEFT_SUPERIOR.
#ffmpeg -f x11grab -framerate 50 -video_size $RESOLUTION -i :0.0+$LEFT_SUPERIOR -f alsa -i pulse:0 -f alsa -i pulse:1 -filter_complex "[0:v]hue=s=0[outv];[1:a][2:a]amerge=inputs=2[a]" -map '[outv]' -map "[a]" -ac 2 -r 30 -b:a 64k $FINAL_NAME
