#!/bin/bash

#              _ _
#   __ _ _   _(_) |_ __ _     _____  _____
#  / _` | | | | | __/ _` |   / _ \ \/ / _ \
# | (_| | |_| | | || (_| |  |  __/>  <  __/
#  \__, |\__,_|_|\__\__,_|___\___/_/\_\___|
#  |___/                |_____|

# para ejecutar el programita de guita

python /data/repos/control-guita/main.py
