#!/bin/sh

#  _       _ _
# (_)_ __ (_) |_     _ __ ___ _ __   ___
# | | '_ \| | __|   | '__/ _ \ '_ \ / _ \
# | | | | | | |_    | | |  __/ |_) | (_) |
# |_|_| |_|_|\__|___|_|  \___| .__/ \___/
#              |_____|       |_|

#
# giving a folder I want to make a github repo
# once I've created the repository in github I
# run this script giving as argument the remote
# github repo name

remote_repository=$1

git init &&
  git add . &&
  git branch -M main &&
  git remote add origin git@github.com:"$remote_repository" &&
  git push -u origin main
