#!/bin/sh

#                           _           _   _                  
#  _ __ ___  _ __   ___    | |__   ___ | |_| | _____ _   _ ___ 
# | '_ ` _ \| '_ \ / __|   | '_ \ / _ \| __| |/ / _ \ | | / __|
# | | | | | | |_) | (__    | | | | (_) | |_|   <  __/ |_| \__ \
# |_| |_| |_| .__/ \___|___|_| |_|\___/ \__|_|\_\___|\__, |___/
#           |_|       |_____|                        |___/     

# 
# Organizo los Hotkeys que uso con el sxhkd

case "$1" in
  Left) mpc -q prev;;
  Right) mpc -q next;;
  Up) mpc -q toggle;;
  Down) mpc -q stop;;
esac

# Reseteo el dwmblocks
pkill -RTMIN+1 dwmblocks;
