#!/bin/sh

# Comandos para reemplazar nombres con find
# USAGE parallel renaming_find {} ::: "$(find -name "*.mp3" -exec basename {} \;)"
# USAGE: ""find . -maxdepth 1 -name "..." -exec renaming {} \;""

## Cambiar espacios por "_" y de mayúsculas a minúsculas
#mv "$1" "$(echo "$1" | tr " " "_" | tr [:upper:] [:lower:])"

mv "$1" "$(echo "$1"| sed -r 's/-na//g')"

#mv "$1" "$(echo "$1" | sed "s/^[0-9][0-9]-//g")"
#mv "$1" "$(echo "$1" | sed "s/^_//g")"
#mv "$1" "$(echo "$1" | sed "s/_-_/-/g")"

## Cambiar "(" --> "_" y ")" --> ""   NO PARENTESIS
#mv "$1" "$(echo "$1" | tr "(" "_" | tr -d ")")"
#mv "$1" "$(echo "$1" | tr -d "'")"

