#!/bin/sh

# Comandos para reemplazar nombres con find
# USAGE: ""find . -maxdepth 1 -name "..." -exec renaming {} \;""

## Cambiar espacios por "_" y de mayúsculas a minúsculas
#mv "$1" "$(echo "$1" | tr " " "_" | tr [:upper:] [:lower:])"

mv "$1" "$(echo "$1"| sed -r 's/dwm_//g')"

#mv "$1" "$(echo "$1" | sed -r "s/^([0-9]{1,2} - )*//g")"

## Cambiar "(" --> "_" y ")" --> ""   NO PARENTESIS
#mv "$1" "$(echo "$1" | tr "(" "_" | tr -d ")")"

