#!/bin/sh

#  _                      _             _
# | |_ ___ _ __ _ __ ___ (_)_ __   __ _| |
# | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | |
# | ||  __/ |  | | | | | | | | | | (_| | |
#  \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_|
#

# Simple script para generar una terminal en el medio de la pantalla de un tamaño custom

falacritty -o window.dimensions.columns=110 -o window.dimensions.lines=30
