#!/bin/sh

# TR_APP_VERSION --> 3.00
# TR_TIME_LOCALTIME --> Tue Jun 23 13:38:25 2020
# TR_TORRENT_DIR --> /data/torrents/torrent_files/
# TR_TORRENT_HASH --> 4a52e9f73ba3032fbc5da46f7b89302c741352c
# TR_TORRENT_ID --> 8
# TR_TORRENT_NAME --> primer directorio sin root  "Avenger (2000)"

SOUND="/data/music/sounds/beep.mp3"
mpv --quiet $SOUND > /dev/null
notify-send "Torrent Done:" "$TR_TORRENT_NAME" 2> $LOGS/torrentdone.log ;

is_movie () {
# Si es una película, la manda a la carpta de películas e intenta bajar subtítulo
	[ -d "/data/peliculas" ] && dir_pelis="/data/peliculas" || exit 1;
	peli="$(find "$TR_TORRENT_DIR$TR_TORRENT_NAME" -name "*.mp4" -o -name "*.mkv" -o -name "*.avi")"
	if [ -f $peli ];
	then transmission-remote -t$TR_TORRENT_ID --move $dir_pelis &> /dev/null && notify-send "📽 $TR_TORRENT_NAME" "📽   --> $dir_pelis  ";
		subdl --existing=bypass "$dir_pelis/$TR_TORRENT_NAME$(basename "$peli")" &> /dev/null && notify-send "Se bajó subtítulo" || notify-send "Falló el subtítulo"
	else
		exit 1;
	fi
}
is_movie
