#!/bin/sh

TORRENTDONE="$HOME_LOCAL/scripts/torrentdone"

pgrep -x transmission-da > /dev/null || (transmission-daemon && notify-send "Starting transmission daemon.." && sleep 3)
transmission-remote -a "$@" --torrent-done-script $TORRENTDONE && notify-send "Torrent added"
