#!/bin/sh

TORRENTDONE="$HOME_LOCAL/scripts/torrentdone"

pgrep -x transmission-da > /dev/null || (transmission-daemon && notify-send "Starting transmission daemon.." && sleep 3)
transmission-remote -a "$@" --torent-done-script $TORRENTDONE && notify-send "Transmission-daemon" "Torrent added."
