#!/bin/sh

# TR_APP_VERSION
# TR_TIME_LOCALTIME
# TR_TORRENT_DIR
# TR_TORRENT_HASH
# TR_TORRENT_ID
# TR_TORRENT_NAME

SOUND="/data/music/sounds/beep.mp3"

mpv --quiet $SOUND > /dev/null
dunstify -r 1234 "Torrent Done:" "$TR_TORRENT_NAME" 2> $LOGS/torrentdone.log
