#!/bin/sh

#
# __      ____ _  ___ ___  _ __ ___        _ __ ___   __ _ _ __
# \ \ /\ / / _` |/ __/ _ \| '_ ` _ \ _____| '_ ` _ \ / _` | '_ \
#  \ V  V / (_| | (_| (_) | | | | | |_____| | | | | | (_| | |_) |
#   \_/\_/ \__,_|\___\___/|_| |_| |_|     |_| |_| |_|\__,_| .__/
#                                                         |_|

# Map the tablet to one output
#

OUTPUT=$(xrandr | grep -e " connected " | cut -d" " -f1 | tr -d " " | tr " " "\n" | dmenu -fn "$dmenu_font" -p "Pantalla a usar:?")

if [ -n "$OUTPUT" ]; then
  xsetwacom --set "Wacom Intuos S Pen stylus" MapToOutput "$OUTPUT" && \
    dunstify "✏ Mapeado a " "✏ $OUTPUT"
fi
