#!/bin/sh

# __        ___    _     _     ____   _    ____  _____ ____
# \ \      / / \  | |   | |   |  _ \ / \  |  _ \| ____|  _ \
#  \ \ /\ / / _ \ | |   | |   | |_) / _ \ | |_) |  _| | |_) |
#   \ V  V / ___ \| |___| |___|  __/ ___ \|  __/| |___|  _ <
#    \_/\_/_/   \_\_____|_____|_| /_/   \_\_|   |_____|_| \_\

DIRECTORY="$HOME/pictures/wallpaper"
WALLPAPER="wall.jpg"

xwallpaper --stretch "$DIRECTORY/$WALLPAPER"
#xwallpaper --center "$WALLPAPER"

