[cursor]
style = "Beam"

[env]
TERM = "alacritty"

[font]
size = 10
offset = {x = 0, y = 1}
normal = {family = "Terminess Nerd Font Mono", style = "Regular"}
bold = {family = "Terminess Nerd Font Mono", style = "Bold"}
italic = {family = "Terminess Nerd Font Mono", style = "Italic"}
bold_italic = {family = "Terminess Nerd Font Mono", style = "Bold Italic"}

[keyboard]
bindings = [
{key = "K", mods = "Control|Shift", action = "ScrollPageUp"},
{key = "J", mods = "Control|Shift", action = "ScrollPageDown"},
{key = "V", mods = "Alt",action = "Paste"},
]

[window]
opacity = 0.9

[colors.primary]
foreground = "#22ff22"
background = "#052005"
