require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.colorscheme"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.illuminate"
require "user.alpha"
require "user.lsp"
require "user.dap"
require "user.tildes_setup"
require "user.rainbow-delimiters"
require "user.colorizer"
require "user.indentline" -- After colorscheme
require "user.harpoon"
require "user.registers"
-- require "user.luasnip"
-- require "user.bufferline" -- para borrar

-- my stuff
require "user.hop"
require "programming_autocommands"
require "my"
require "snippets.my_snippets"
